name: Type check and lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  typecheck-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate prisma
        run: npx prisma generate

      - name: Type check and lint
        run: pnpm run typecheck && pnpm run lint
        env:
          # use dummy env variables to bypass t3-env check
          DATABASE_URL: mysql://test:xxxx@xxxxxxxxx:3306/test
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          RESEND_API_KEY: xxxxxxxx
